import { getDb } from '../../db/database.js';
import { resolveSpintax, substituteVars } from './spintax.js';
import { io } from '../../server.js';
import { systemLog } from '../../utils/logger.js';

export async function startGeminiWorkerPool(leadIds, prompt, apiKey, poolId) {
  const db = getDb();

  const queue = [...leadIds];
  const results = [];

  const WORKER_COUNT = Math.min(13, queue.length);
  const TARGET_DELAY = 61000; // 61 seconds per worker

  console.log(`[Gemini Pool] Starting ${WORKER_COUNT} workers for ${queue.length} tasks (Limit: 15 RPM)...`);

  const workerLoop = async (workerId) => {
    // Равномерно распределяем старт 13 воркеров по одной минуте (каждые ~4.6 сек)
    await new Promise(r => setTimeout(r, workerId * (60000 / WORKER_COUNT)));

    while (queue.length > 0) {
      if (global.aiGenPoolId && global.aiGenPoolId !== poolId) {
        console.log(`[Worker ${workerId}] Pool superseded. Exiting.`);
        break;
      }

      const leadId = queue.shift();
      if (!leadId) break;

      const leads = await db`SELECT * FROM leads WHERE id = ${leadId}`;
      const lead = leads[0];
      if (!lead || lead.status === 'ready_to_send') continue;

      const startTime = Date.now();
      console.log(`[Worker ${workerId}] Started lead #${lead.id}`);

      let attempts = 0;
      let success = false;
      let lastError = null;

      while (attempts < 3 && !success) {
        attempts++;
        try {
          const filledSystem = substituteVars(prompt.system_prompt || '', lead);
          const userPrompt = substituteVars(
            `Оголошення:\nЗаголовок: ${lead.title || ''}\nТелефон/Ник: ${lead.ig_username ? '@' + lead.ig_username : (lead.phone || '')}\nТекст: ${(lead.ad_text || '').substring(0, 500)}\nМісто: ${lead.city || 'невідоме'}\n\n${prompt.message_template}`,
            lead
          );

          const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
              systemInstruction: { parts: [{ text: filledSystem || 'You are a helpful assistant.' }] },
              generationConfig: { temperature: 0.7 }
            })
          });

          const data = await response.json();

          if (!response.ok) {
            throw new Error(`Gemini API Error: ${data.error?.message || response.statusText}`);
          }

          const rawMessage = data.candidates?.[0]?.content?.parts?.[0]?.text;
          if (!rawMessage) throw new Error('No content generated by Gemini');

          const message = resolveSpintax(rawMessage);

          await db`UPDATE leads SET ai_message = ${message} WHERE id = ${lead.id}`;

          if (global.aiGenStatus) global.aiGenStatus.done++;
          results.push({ leadId: lead.id, leadName: lead.name, leadPhone: lead.phone, message });
          io.emit('ai:generated', { leadId: lead.id, message });

          console.log(`[Worker ${workerId}] Success lead #${lead.id} on attempt ${attempts}.`);
          success = true;
        } catch (err) {
          lastError = err;
          const isTransient = err.message.includes('high demand') || err.message.includes('Quota') || err.message.includes('503') || err.message.includes('429');
          if (isTransient && attempts < 3) {
            console.log(`[Worker ${workerId}] Transient error on lead #${lead.id}: ${err.message}. Retrying in 60s...`);
            await new Promise(r => setTimeout(r, 60000));
          } else {
            break;
          }
        }
      }

      if (!success) {
        if (global.aiGenStatus) global.aiGenStatus.errors++;
        console.error(`[Worker ${workerId}] Failed lead #${lead.id} after ${attempts} attempts:`, lastError?.message);
        await systemLog('ai', 'error', `Gemini Worker Error on lead #${lead.id}: ${lastError?.message}`);
        io.emit('ai:error', { leadId, error: lastError?.message });
      }

      const elapsed = Date.now() - startTime;
      const sleepTime = TARGET_DELAY - elapsed;

      if (sleepTime > 0 && queue.length > 0) {
        console.log(`[Worker ${workerId}] Sleeping for ${sleepTime}ms...`);
        await new Promise(r => setTimeout(r, sleepTime));
      }
    }
  };

  const promises = [];
  for (let i = 1; i <= WORKER_COUNT; i++) {
    promises.push(workerLoop(i));
  }

  await Promise.all(promises);
  console.log('[Gemini Pool] All tasks completed.');

  if (global.aiGenStatus && global.aiGenPoolId === poolId) {
    global.aiGenStatus.active = false;
    setTimeout(() => {
      if (global.aiGenStatus && !global.aiGenStatus.active && global.aiGenPoolId === poolId) {
        global.aiGenStatus = null;
      }
    }, 3000);
  }

  io.emit('ai:batch-done', { results });
}
